version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend-container
    image: backend-image
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app 
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend-container
    image: frontend-image
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    